<div class="hero-unit">
    <h1>¿Qué es Fasedata?</h1>
    <dl class="dl-horizontal">
            Es un concepto creado por tres jóvenes penquistas (<a href="http://maps.google.com/maps?q=Concepci%C3%B3n,+Chile&hl=es&ie=UTF8&sll=-36.818938,-73.050319&sspn=0.149239,0.338173&t=h&hnear=Concepci%C3%B3n,+Provincia+de+Concepci%C3%B3n,+Regi%C3%B3n+del+B%C3%ADo-B%C3%ADo,+Chile&z=12" target="_blank">Concepción, Chile</a>) el cual consiste en la utilización de la <code>creatividad</code> y la <code>innovación</code> de las <code>tecnologías web</code> para dar solución a las necesidades de nuestros clientes y sobrepasar las expectativas establecidas por ellos mismos.
    </dl>		
    <dl class="dl-horizontal">
            Nuestra experiencia de trabajar en distintas empresas del rubro del <code>desarrollo web</code> en Chile, nos permite conocer lo bueno y lo malo del mercado. Esto nos motiva más aún a no cometer los mismos errores de las empresas del rubro y saber como actuar ante los desafios impuestos.
    </dl>
    <dl class="dl-horizontal">
    Las tecnologías que ocupamos se pueden resumir en las siguientes:
    </dl>		
    <ul>
            <li>XHTML</li>
            <li>CSS</li>
            <li>JavaScript y jQuery</li>			
            <li>PHP (Zend Framework)</li>
            <li>MySQL</li>			
            <li>SQL Server</li>			
    </ul>	
    <dl class="dl-horizontal">
    Si estas interesado en que desarrollemos tus proyectos no dudes en contactarnos a <a href="mailto:info@fasedata.info">info@fasedata.info</a>
    </dl>			
</div>	