<h2>Estadisticas</h2>
<div class="well btn-warning alto">
    <div class="span3">
        <h2>test</h2>
        <p>50% de rebotes</p>
    </div>
    <div class="span2">
        <h3>test</h3>
        <p>50% de rebotes</p>
    </div>    
    <div class="span2">
        <h3>test</h3>
        <p>50% de rebotes</p>
    </div>    
    <div class="span2">
        <h3>test</h3>
        <p>50% de rebotes</p>
    </div>    
    <div class="span2">
        <h3>test</h3>
        <p>50% de rebotes</p>
    </div>    
</div>
<h2>Historial de acciones</h2>
<table class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>Modulo</th>
            <th>Autor</th>
            <th>Accion</th>
            <th>Fecha</th>
            <th>Hora</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Noticias</td>
            <td>Jonathan</td>
            <td>Eliminar</td>
            <td>13-05-2012</td>
            <td>15:30:10</td>
        </tr>
        <tr>
            <td>Noticias</td>
            <td>Jonathan</td>
            <td>Eliminar</td>
            <td>13-05-2012</td>
            <td>15:30:10</td>
        </tr>
        <tr>
            <td>Noticias</td>
            <td>Jonathan</td>
            <td>Eliminar</td>
            <td>13-05-2012</td>
            <td>15:30:10</td>
        </tr>
    </tbody>
</table>

