
<div class="well well-large alto">
    <div class="span3">
        <h4>Modulos</h4>
        <ul>
            <li><a href="#">Modulo 1</a></li>
            <li><a href="#">Modulo 1</a></li>
            <li><a href="#">Modulo 1</a></li>
            <li><a href="#">Modulo 1</a></li>
        </ul>
    </div>
    <div class="span3">
        <h4>Mi perfil</h4>
        <ul>
            <li><a href="#">Modulo 1</a></li>
            <li><a href="#">Modulo 1</a></li>
            <li><a href="#">Modulo 1</a></li>
            <li><a href="#">Modulo 1</a></li>
        </ul>
    </div>
</div>
<div class="row pull-right">
    <h4><small>Todos los derechos reservados</small></h4><br />
</div>