<div class="navbar">
    <div class="navbar-inner">
        <div class="container">
            <a class="brand" href="#">Nombre proyecto</a>
            <ul class="nav">
                <li><a href="#">Tablero</a></li>
                <li class="divider-vertical"></li> 
                <li class="dropdown">
                <a href="#"class="dropdown-toggle"data-toggle="dropdown">
                    Modulos<b class="caret"></b>
                </a>
                    <ul class="dropdown-menu">
                        <li class="nav-header">Personalizados</li>
                        <li><a href="#"><i class="icon-list-alt"></i> Modulo 1</a></li>
                        <li><a href="#"><i class="icon-list-alt"></i> Modulo 1</a></li>
                        <li class="divider"></li>
                        <li class="nav-header">Generales</li>
                        <li><a href="#"><i class="icon-list-alt"></i> Modulo 1</a></li>
                    </ul> 
                </li>
                <li class="divider-vertical"></li>  
            </ul>
            <div class="pull-right">
                <ul class="nav">
                    <li class="divider-vertical"></li> 
                    <li>
                        <a href="#"  rel="tooltip" href="#" data-original-title="first tooltip">Actualizaciones</a>
                    </li>
                    <li class="divider-vertical"></li> 
                </ul>
            </div>
        </div>
    </div>
</div>