<div class="row">
    <div class="span4">
        <img alt="" src="http://placehold.it/200x50">
    </div>
    <div class="span8">
        <div class="row pull-right">
            Hola <strong>Jonathan Ramírez</strong> |
            <a href="#">Mi perfil</a> |
            <a href="#">Cerrar sesión</a>
        </div><br />
        <div class="row pull-right">
            <a href="#">Configuración</a> |
            <a href="#">Usuarios</a> |             
            <a href="#">Ayuda</a>           
        </div>
    </div>
</div>