<?php echo $this->doctype();echo "\n"; ?>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />    
<?php echo $this->headTitle();echo "\n"; ?>
<?php echo $this->headMeta();echo "\n"; ?>
<?php echo $this->headLink();echo "\n"; ?>
<?php echo $this->headScript();echo "\n"; ?>    
</head>
<body class="distinto">
    
<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container-fluid">
            <a href="#" class="brand">Fasedata</a>
            <div class="nav-collapse">
                <ul class="nav pills-right">
                    <li><a href="#"><span class="badge badge-warning">Actualizaciones</span></a></li>
                </ul>
                <ul class="nav nav-list pull-right">
                    <li class="dropdown">
                        <a href="#"class="dropdown-toggle" data-toggle="dropdown">
                            Bienvenido <strong>Jonathan Ramírez</strong>
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="#"><i class="icon-user"></i> Mi perfil</a></li>
                            <li><a href="#"><i class="icon-off"></i> Cerrar sesión</a></li>                       
                            <li class="divider"></li>
                            <li><a href="#"><i class="icon-question-sign"></i> Ayuda</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
<div class="container-fluid">
    <div class="page-header">
        <h1>Tablero <small>una completa herramienta CMS para tus clientes</small></h1>
    </div>        
    <div class="row-fluid">
        <div class="span3">
            <div class="well sidebar-nav">
                <ul class="nav nav-list">
                    <li class="nav-header">Fasedata</li>
                    <li><a href="#"><i class="icon-home"></i>Tablero</a></li>
                    <li><a href="#"><i class="icon-home"></i>Configuración</a></li>
                    <li class="nav-header">Modulos</li>
                    <li><a href="#"><i class="icon-user"></i>Usuarios</a></li>
                    <li><a href="#"><i class="icon-file"></i>Noticias</a></li>
                    <li><a href="#"><i class="icon-list-alt"></i>Paginas editables</a></li>                    
                    <li><a href="#"><i class="icon-file"></i>Empresa</a></li>                    
                    <li><a href="#"><i class="icon-list-alt"></i>Galería de fotos</a></li>
                    <li class="nav-header">Mi Cuenta</li>
                    <li><a href="#"><i class="icon-user"></i> Mi perfil</a></li>
                    <li class="divider"> </li>
                    <li><a href="#"><i class="icon-question-sign"></i>Ayuda</a></li>
                    
                </ul>
            </div>
        </div>
        <div class="span9"> 
            <div class="well btn-warning">
                <div class="row">
                    <div class="span4">
                        <h1>Estadísticas</h1>
                        De los distintos módulos
                    </div>
                    <div class="span1">
                        <h2>Hoy</h2>
                        25 visitas
                    </div>
                    <div class="span1">
                        <h2>Ayer</h2>
                        37 visitas
                    </div>
                    <div class="span1">
                        <h2>Ayer</h2>
                        37 visitas
                    </div>
                </div>
            </div> 
            <ul class="thumbnails">
                <li class="span4">
                    <div class="thumbnail">
                        <img alt="" src="http://placehold.it/460x180">
                        <div class="caption">                   
                            <h4>Thumbnail label</h4>
                            <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                            <p> 
                                <a class="btn btn-success btn-mini" href="#">Configurar</a> 
                                <a class="btn btn-danger btn-mini" href="#">Desactivar</a> 
                            </p>
                        </div>
                    </div>
                </li>
                <li class="span4">
                    <div class="thumbnail">
                        <img alt="" src="http://placehold.it/460x180">
                        <div class="caption">                   
                            <h4>Thumbnail label</h4>
                            <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                            <p> 
                                <a class="btn btn-success btn-mini" href="#">Configurar</a> 
                                <a class="btn btn-danger btn-mini" href="#">Desactivar</a> 
                            </p>
                        </div>
                    </div>
                </li>  
                <li class="span4">
                    <div class="thumbnail">
                        <img alt="" src="http://placehold.it/460x180">
                        <div class="caption">                   
                            <h4>Thumbnail label</h4>
                            <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                            <p> 
                                <a class="btn btn-success btn-mini" href="#">Configurar</a> 
                                <a class="btn btn-danger btn-mini" href="#">Desactivar</a> 
                            </p>
                        </div>
                    </div>
                </li>                
            </ul>
                <div class="pagination">
                    <ul>
                    <li><a href="#">Prev</a></li>
                    <li class="active">
                    <a href="#">1</a>
                    </li>
                    <li><a href="#">2</a></li>
                    <li><a href="#">3</a></li>
                    <li><a href="#">4</a></li>
                    <li><a href="#">Next</a></li>
                    </ul>
                </div>
        </div>
    </div>
</div>         
                              
                              <?php /*echo $this->layout()->content;*/ ?>	
</body>
</html>