<?php echo $this->doctype();echo "\n"; ?>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />    
<?php echo $this->headTitle();echo "\n"; ?>
<?php echo $this->headMeta();echo "\n"; ?>
<?php echo $this->headLink();echo "\n"; ?>
<?php echo $this->headScript();echo "\n"; ?>    
</head>
<body>
<div class="container">	
	<div class="navbar">
		<div class="navbar-inner">
			<div class="container">		
				<a class="brand" href="/" title="Desarrollo de Aplicaciones Web y Sitios Web personalizados">Fasedata</a>			
				<!--<ul class="nav">		
					<li class="divider-vertical"></li>					
					<li><a href="/proyectos/">Proyectos</a></li>
					<li class="divider-vertical"></li>				
					<li><a href="/contactenos/">Contáctenos</a></li>	
					<li class="divider-vertical"></li>	
				</ul>-->
			</div>
		</div>	
	</div>
    <?php echo $this->layout()->content; ?>
</div>	
</body>
</html>