<ul class="breadcrumb">
    <li><a href="#">Tablero</a> <span class="divider">/</span></li>
    <li><a href="#">Modulos</a> <span class="divider">/</span></li>
    <li class="active">Nombre del modulo</li>
</ul>
<h2>Nombre del modulo</h2>
<h2><small>Este modulo sirve para agregar noticias en el sitio web nos ayuda a tener actualizados a nuestros futuros visitantes</small></h2>
<br />
<div class="row-fluid">
    <div class="span9">
        <table class="table table-striped table-bordered table-condensed">
            <thead>
                <tr>
                    <th>Titulo</th>
                    <th class="span1">Autor</th>
                    <th class="span1">Accion</th>
                    <th class="span1">Fecha</th>
                    <th class="span2 masgrande2">Acciones</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Jefes de las bancadas de la Concertación "congelan" relación con el Gobierno y se restan de cena con Larroulet </td>
                    <td>Jonathan</td>
                    <td>Eliminar</td>
                    <td>13-05-2012</td>
                    <td>
                        <a href="#" class="btn btn-mini"><i class="icon-pencil"></i> Editar</a>
                        <a href="#" class="btn btn-mini"><i class="icon-trash"></i> Eliminar</a>
                    </td>
                </tr>
                <tr>
                    <td>Jefes de las bancadas de la Concertación "congelan" relación con el Gobierno y se restan de cena con Larroulet </td>
                    <td>Jonathan</td>
                    <td>Eliminar</td>
                    <td>13-05-2012</td>
                    <td>
                        <a href="#" class="btn btn-mini"><i class="icon-pencil"></i> Editar</a>
                        <a href="#" class="btn btn-mini"><i class="icon-trash"></i> Eliminar</a>
                    </td>
                </tr>
                <tr>
                    <td>Jefes de las bancadas de la Concertación "congelan" relación con el Gobierno y se restan de cena con Larroulet </td>
                    <td>Jonathan</td>
                    <td>Eliminar</td>
                    <td>13-05-2012</td>
                    <td>
                        <a href="#" class="btn btn-mini"><i class="icon-pencil"></i> Editar</a>
                        <a href="#" class="btn btn-mini"><i class="icon-trash"></i> Eliminar</a>
                    </td>
                </tr>
                <tr>
                    <td>Jefes de las bancadas de la Concertación "congelan" relación con el Gobierno y se restan de cena con Larroulet </td>
                    <td>Jonathan</td>
                    <td>Eliminar</td>
                    <td>13-05-2012</td>
                    <td>
                        <a href="#" class="btn btn-mini"><i class="icon-pencil"></i> Editar</a>
                        <a href="#" class="btn btn-mini"><i class="icon-trash"></i> Eliminar</a>
                    </td>
                </tr>
                <tr>
                    <td>Jefes de las bancadas de la Concertación "congelan" relación con el Gobierno y se restan de cena con Larroulet </td>
                    <td>Jonathan</td>
                    <td>Eliminar</td>
                    <td>13-05-2012</td>
                    <td>
                        <a href="#" class="btn btn-mini"><i class="icon-pencil"></i> Editar</a>
                        <a href="#" class="btn btn-mini"><i class="icon-trash"></i> Eliminar</a>
                    </td>
                </tr>
                <tr>
                    <td>Jefes de las bancadas de la Concertación "congelan" relación con el Gobierno y se restan de cena con Larroulet </td>
                    <td>Jonathan</td>
                    <td>Eliminar</td>
                    <td>13-05-2012</td>
                    <td>
                        <a href="#" class="btn btn-mini"><i class="icon-pencil"></i> Editar</a>
                        <a href="#" class="btn btn-mini"><i class="icon-trash"></i> Eliminar</a>
                    </td>
                </tr>
                <tr>
                    <td>Jefes de las bancadas de la Concertación "congelan" relación con el Gobierno y se restan de cena con Larroulet </td>
                    <td>Jonathan</td>
                    <td>Eliminar</td>
                    <td>13-05-2012</td>
                    <td>
                        <a href="#" class="btn btn-mini"><i class="icon-pencil"></i> Editar</a>
                        <a href="#" class="btn btn-mini"><i class="icon-trash"></i> Eliminar</a>
                    </td>
                </tr>
            </tbody>
        </table>
        <div class="pagination pagination-right">
            <ul>
                <li><a href="#">Prev</a></li>
                <li class="active">
                <a href="#">1</a>
                </li>
                <li><a href="#">2</a></li>
                <li><a href="#">3</a></li>
                <li><a href="#">4</a></li>
                <li><a href="#">Next</a></li>
            </ul>
        </div>        
    </div>
    <div class="span3 izquierda">
        <a href="#" class="btn btn-success btn-large">Nuevo Registro</a>
        <hr />
        <h3>Estadisticas</h3><br />
        <div class="well well-small">
            Registros totales: 50 datos<br />
            Registros leidos: 30 datos<br />
            Total vistas: 1500 vistas<br />
            Porcentaje diario: 0,05 por día
        </div>
        <h3>Modulos relacionados</h3><br />
        <ul>
            <li><a href="#">Comentarios</a></li>
            <li><a href="#">Servicios</a></li>
        </ul>
    </div>
</div>