<ul class="breadcrumb">
    <li><a href="#">Tablero</a> <span class="divider">/</span></li>
    <li class="active">Modulos</li>
</ul>
<div class="row">
    <div class="span3 well well-small">
        <h2>Modulo1</h2>
        <h3><small>Hay <strong>60</strong> registros</small></h3>
        <p>Este modulo sirve para agregar noticias en el sitio web nos ayuda a tener actualizados a nuestros futuros visitantes</p>
        <a href="/sistema/modulo/detalle" class="btn btn-primary">Entrar</a>
    </div>
</div>